### ISSUE TITLE
[feature request] Add a tooltip!

### ISSUE THREAD

**Issue by CxRes** [Koooooo-7/docsify-corner#6]
Please provide an option to specify a tooltip for the icon!

**Comment by Koooooo-7** [comment]
Could u plz give more details about it ?

**Comment by CxRes** [comment]
When you hover on the button you can have a optional pop-up message, such as "open with Gitlab".

**Comment by Koooooo-7** [comment]
I see, I will make it later.

**Comment by Koooooo-7** [comment]
Hi, I  update it in `v1.0.4`(the latest version for now) now, you can use `title` to do the trick. 🚀

**Comment by CxRes** [comment]
Thanks!
