### ISSUE TITLE
Url config invalid

### ISSUE THREAD

**Issue by Cmdone** [Koooooo-7/docsify-corner#7]
Config like this:

```html
<script src="//cdn.jsdelivr.net/npm/docsify-corner/dist/docsify-corner.min.js"></script>

<script>
  window.$docsify = {
      repo:'true',
      corner: {
        url: "https://www.google.com", 
        icon: "gitlab"
      },
  };
</script>
```

This can show correct gitlab icon, but click just jump to "undefined"

Then when I change to:

```html
<script src="//cdn.jsdelivr.net/npm/docsify-corner@1.0.3/dist/docsify-corner.min.js"></script>
```

This bug never exist

**Comment by Koooooo-7** [comment]
thx for ur report, I will take a look on it soon.

**Comment by Koooooo-7** [comment]
it's fixed rn, please check it again.

**Comment by Cmdone** [comment]
> it's fixed rn, please check it again.

It just fiixed when I specifing `docsify-corner@1.0.6`, does it correct?

**Comment by Koooooo-7** [comment]
yep.
