### ISSUE TITLE
The official target: '_self' option doesn't work.

### ISSUE THREAD

**Issue by foxcodegit** [Koooooo-7/docsify-corner#9]
Hello, thanks for your good plugin.
Actually the official '_self' doesn't work. 
I have tried everything, but I am having trouble getting it to reflect at all.
Could you please allow me to add/override '_self' in the options for this plugin?

like this ↓

```
      corner: {
        url: "/",
        icon: "origin.png",
        target: "_self",
      },
```

best regard.

**Comment by Koooooo-7** [comment]
Hi @foxcodegit , I thought the [`cornerexternallinktarget`](https://docsify.js.org/#/configuration?id=cornerexternallinktarget) should work.
No worry, I add the `target` config in `docsify-corner` as well now.
You can use the latest version (`v1.0.7`) to do the trick. 😺

**Comment by foxcodegit** [comment]
Thank you. I still couldn't do it the official way, but your plugin update changed target='_blank' to '_self' without any problems. ( I reflected the postscript source locally because the dist distribution was not yet available ).

<img src='https://user-images.githubusercontent.com/39505587/171968216-96e7b708-6fdd-4288-8937-0ec757b96198.jpg' width='500px'>

**Comment by Koooooo-7** [comment]
no problem. I think the new v1.0.7 published lagged on the cdn stuff, it should work soon.

and I got a fix on that official also.
I think you can use the official one, either the corner one, whichever you want in the next released docsify version.

**Comment by foxcodegit** [comment]
Really. I didn't know that you are a contributor in docsify official. That's helpful. Thank you.

**Comment by Koooooo-7** [comment]
👌
